stages:
  data:
    cmd: chinook_db -e ${elevation} -s ${temps} -t ${data} -c ${context}
    deps:
      - ../../../mirrorverse/chinook/db.py
    params:
      - elevation
      - temps
      - data
      - context
    outs:
      - ${data}
      - ${elevation}
      - ${temps}
      - ${context}
  states:
    cmd: chinook_monthly_states -d ${data} -c ${context} -o .  -r ${resolution} -ts ${training_size}
    deps:
      - ../../../mirrorverse/chinook_monthly/states.py
      - ../../../mirrorverse/chinook/utils.py
      - ${data}
      - ${context}
    params: 
      - data
      - context
      - resolution
      - training_size
    outs:
      - training_states.csv
      - testing_states.csv
  train_drift_movement:
    cmd: chinook_monthly_train -n DriftMovementLeaf -tr training_states.csv -te testing_states.csv -t ${temps} -e ${elevation} -m .
    deps:
      - ../../../mirrorverse/tree.py
      - ../../../mirrorverse/chinook_monthly/tree/drift_movement.py
      - ../../../mirrorverse/chinook_monthly/train.py
      - training_states.csv
      - testing_states.csv
      - ${temps}
      - ${elevation}
    params:
      - temps
      - elevation
    outs:
      - DriftMovementLeaf.pkl
      - DriftMovementLeaf.csv
  bundle_models:
    cmd: mirrorverse_bundle_models -m .
    deps:
      - DriftMovementLeaf.pkl
    outs:
      - models.pkl
  