stages:
  data:
    cmd: chinook_db -e ${elevation} -s ${temps} -t ${data}
    deps:
      - ../../../mirrorverse/chinook/db.py
    params:
      - elevation
      - temps
      - data
    outs:
      - ${data}
      - ${elevation}
      - ${temps}
  states:
    cmd: chinook_states -d ${data} -o .  -r ${resolution} -mae ${max_allowable_error} -mad ${min_allowable_distance} -ts ${training_size}
    deps:
      - ../../../mirrorverse/chinook/states.py
      - ../../../mirrorverse/chinook/utils.py
      - ${data}
    params: 
      - data
      - resolution
      - max_allowable_error
      - min_allowable_distance
      - training_size
    outs:
      - training_states.csv
      - testing_states.csv
  train_drift_movement:
    cmd: chinook_train -n DriftMovementLeaf -tr training_states.csv -te testing_states.csv -t ${temps} -e ${elevation} -m .
    deps:
      - ../../../mirrorverse/tree.py
      - ../../../mirrorverse/chinook/tree/drift_movement.py
      - ../../../mirrorverse/chinook/train.py
      - training_states.csv
      - testing_states.csv
      - ${temps}
      - ${elevation}
    params:
      - temps
      - elevation
    outs:
      - DriftMovementLeaf.pkl
  train_run_movement:
    cmd: chinook_train -n RunMovementLeaf -tr training_states.csv -te testing_states.csv -t ${temps} -e ${elevation} -m .
    deps:
      - ../../../mirrorverse/tree.py
      - ../../../mirrorverse/chinook/tree/run_movement.py
      - ../../../mirrorverse/chinook/train.py
      - training_states.csv
      - testing_states.csv
      - ${temps}
      - ${elevation}
    params:
      - temps
      - elevation
    outs:
      - RunMovementLeaf.pkl
  train_run_heading:
    cmd: chinook_train -n RunHeadingBranch -tr training_states.csv -te testing_states.csv -t ${temps} -e ${elevation} -m .
    deps:
      - ../../../mirrorverse/tree.py
      - ../../../mirrorverse/chinook/tree/run_heading.py
      - ../../../mirrorverse/chinook/train.py
      - training_states.csv
      - testing_states.csv
      - ${temps}
      - ${elevation}
    params:
      - temps
      - elevation
    outs:
      - RunHeadingBranch.pkl
  train_run_or_drift:
    cmd: chinook_train -n RunOrDriftBranch -tr training_states.csv -te testing_states.csv -t ${temps} -e ${elevation} -m .
    deps:
      - ../../../mirrorverse/tree.py
      - ../../../mirrorverse/chinook/tree/run_or_drift.py
      - ../../../mirrorverse/chinook/train.py
      - training_states.csv
      - testing_states.csv
      - ${temps}
      - ${elevation}
    params:
      - temps
      - elevation
    outs:
      - RunOrDriftBranch.pkl
  bundle_models:
    cmd: mirrorverse_bundle_models -m .
    deps:
      - DriftMovementLeaf.pkl
      - RunMovementLeaf.pkl
      - RunHeadingBranch.pkl
      - RunOrDriftBranch.pkl
    outs:
      - models.pkl