stages:
  build:
    cmd: mirrorverse_upload_dimensions -t dates -m ${missing_dimensions} -o status.json
    deps:
      - ../../../mirrorverse/warehouse/commands.py
      - ../../../mirrorverse/warehouse/etls/missing_dimensions.py
      - ../../../mirrorverse/warehouse/etls/dimensions/dates.py
      - ../../../mirrorverse/warehouse/models/dimensions.py
      - ../../../mirrorverse/warehouse/utils.py
      - ${missing_dimensions}
    always_changed: true
    params:
      - missing_dimensions
    outs:
      - status.json