stages:
  states:
    cmd: blob_states -d ${data} -o . -ts ${training_size}
    deps:
      - ../../../mirrorverse/blob/states.py
      - ${data}
    params: 
      - data
      - training_size
    outs:
      - training_states.csv
      - testing_states.csv
  train_blob:
    cmd: blob_train -n BlobRoot -tr training_states.csv -te testing_states.csv -m .
    deps:
      - ../../../mirrorverse/tree.py
      - ../../../mirrorverse/blob/tree/blob_root.py
      - ../../../mirrorverse/blob/train.py
      - training_states.csv
      - testing_states.csv
    outs:
      - BlobRoot.pkl
      - BlobRoot.csv
  group_blob:
    cmd: mirrorverse_group -n BlobRoot.csv -g 10
    deps:
      - ../../../mirrorverse/grouper.py
      - BlobRoot.csv 
    outs:
      - BlobRoot_groupings.csv
      - BlobRoot_statistics.csv
