stages:
  load_depth_data:
    cmd: mirrorverse_chinook_depth --function load_depth_data --output_file depth_data.csv.gz
    deps:
      - ../../../mirrorverse/models/chinook_depth/warehouse.py
    outs:
      - depth_data.csv.gz
  add_depth_classes:
    cmd: mirrorverse_chinook_depth --function add_depth_classes --input_file depth_data.csv.gz --output_file depth_classes.csv.gz --depth_classes "${depth_classes}"
    deps:
      - ../../../mirrorverse/models/chinook_depth/warehouse.py
      - depth_data.csv.gz
    params:
      - depth_classes
    outs:
      - depth_classes.csv.gz
  load_context_data:
    cmd: mirrorverse_chinook_depth --function load_context_data --output_file context_data.csv.gz
    deps:
      - ../../../mirrorverse/models/chinook_depth/warehouse.py
    outs:
      - context_data.csv.gz
  join_in_context_data:
    cmd: mirrorverse_chinook_depth --function join_in_context_data --input_files "depth_classes.csv.gz,context_data.csv.gz" --output_file warehouse_data.csv.gz
    deps:
      - ../../../mirrorverse/models/chinook_depth/warehouse.py
      - depth_classes.csv.gz
      - context_data.csv.gz
    outs:
      - warehouse_data.csv.gz
