stages:
  load_depth_data:
    cmd: mirrorverse_chinook_depth --function load_depth_data --output_file depth_data.csv.gz
    deps:
      - ../../../mirrorverse/models/chinook_depth/data.py
    outs:
      - depth_data.csv.gz
  add_depth_classes:
    cmd: mirrorverse_chinook_depth --function add_depth_classes --input_file depth_data.csv.gz --output_file depth_classes.csv.gz --depth_classes "${depth_classes}"
    deps:
      - ../../../mirrorverse/models/chinook_depth/data.py
      - depth_data.csv.gz
    params:
      - depth_classes
    outs:
      - depth_classes.csv.gz
