stages:
  build:
    cmd: mirrorverse_upload_dimensions -t h3_level_4 -m ${missing_dimensions} -o status.json
    deps:
      - ../../../mirrorverse/warehouse/commands.py
      - ../../../mirrorverse/warehouse/etls/missing_dimensions.py
      - ../../../mirrorverse/warehouse/etls/dimensions/spatial.py
      - ../../../mirrorverse/warehouse/models/dimensions.py
      - ../../../mirrorverse/warehouse/utils.py
      - ${missing_dimensions}
    params:
      - missing_dimensions
    outs:
      - status.json