stages:
  import:
    cmd: mirrorverse_file_import -i elevation -f ${data} -o elevation.csv
    deps:
      - ../../../mirrorverse/docks/commands.py
      - ../../../mirrorverse/docks/elevation.py
      - ${data}
    params:
      - data
    outs:
      - elevation.csv