stages:
  format:
    cmd: mirrorverse_upload_facts -t home_regions -f ${raw_data} -o status.json
    deps:
      - ../../../mirrorverse/warehouse/commands.py
      - ../../../mirrorverse/warehouse/etls/facts/tags.py
      - ../../../mirrorverse/warehouse/models/facts.py
      - ../../../mirrorverse/warehouse/utils.py
      - ${raw_data}
    params: 
      - raw_data
    outs:
      - status.json
  enumerate_missing_dimensions:
    cmd: mirrorverse_enumerate_missing_dimensions -t home_regions -o missing_dimensions.json
    deps:
      - ../../../mirrorverse/warehouse/etls/missing_dimensions.py
      - ../../../mirrorverse/warehouse/utils.py
      - ../../../mirrorverse/warehouse/models/dimensions.py
      - ../../../mirrorverse/warehouse/models/facts.py
      - status.json
    always_changed: true
    outs:
      - missing_dimensions.json