stages:
  states:
    cmd: chinook_states -d ${data} -c ${context} -o .  -r ${resolution} -mae ${max_allowable_error} -mad ${min_allowable_distance} -ts 1
    deps:
      - ../../../mirrorverse/chinook/states.py
      - ../../../mirrorverse/chinook/utils.py
      - ${data}
      - ${context}
    params: 
      - data
      - context
      - resolution
      - max_allowable_error
      - min_allowable_distance
    outs:
      - training_states.csv
  simulate:
    cmd: chinook_simulate -d training_states.csv -t ${temps} -e ${elevation} -m ${model} -si simulation.csv
    deps:
      - ../../../mirrorverse/chinook/simulate.py
      - ../../../mirrorverse/chinook/states.py
      - training_states.csv
      - ${temps}
      - ${elevation}
      - ${model}
    params:
      - temps
      - elevation
      - model
    outs:
      - simulation.csv