# DATA
data: ../data/tag_tracks.csv
temps: ../data/surface_temps.csv
elevation: ../data/bathymetry.csv
context: ../data/context.csv

# MODELS
model: ../train/models.pkl

# CONTEXT
resolution: 4
max_allowable_error: 0.79 # pi / 4
min_allowable_distance: 150 # km